version: 3
services:
  database:
    image: mysql:latest
    container_name: cached-number-service-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  db-adminer:
    image: adminer
    container_name: cached-number-service-mysqladmin
    restart: always
    ports:
      - 8300:8080
  redis:
    image: redis:latest
    container_name: cached-number-service-redis
    restart: always
  application:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    container_name: cached-number-service-app
    ports:
      - 8100:80
    volumes:
      - "../web/:/usr/share/nginx/html"
